/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ListSipIpAccessControlListResponse struct {

	End int32 `json:"end,omitempty"`

	FirstPageUri string `json:"first_page_uri,omitempty"`

	IpAccessControlLists []ApiV2010AccountSipSipIpAccessControlList `json:"ip_access_control_lists,omitempty"`

	NextPageUri string `json:"next_page_uri,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	PreviousPageUri string `json:"previous_page_uri,omitempty"`

	Start int32 `json:"start,omitempty"`

	Uri string `json:"uri,omitempty"`
}

// AssertListSipIpAccessControlListResponseRequired checks if the required fields are not zero-ed
func AssertListSipIpAccessControlListResponseRequired(obj ListSipIpAccessControlListResponse) error {
	for _, el := range obj.IpAccessControlLists {
		if err := AssertApiV2010AccountSipSipIpAccessControlListRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListSipIpAccessControlListResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListSipIpAccessControlListResponse (e.g. [][]ListSipIpAccessControlListResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListSipIpAccessControlListResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListSipIpAccessControlListResponse, ok := obj.(ListSipIpAccessControlListResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListSipIpAccessControlListResponseRequired(aListSipIpAccessControlListResponse)
	})
}
