/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiV2010AccountSipSipCredentialListSipCredential struct {

	// The unique id of the Account that is responsible for this resource.
	AccountSid *string `json:"account_sid,omitempty"`

	// The unique id that identifies the credential list that includes this credential
	CredentialListSid *string `json:"credential_list_sid,omitempty"`

	// The date that this resource was created, given as GMT in RFC 2822 format.
	DateCreated *string `json:"date_created,omitempty"`

	// The date that this resource was last updated, given as GMT in RFC 2822 format.
	DateUpdated *string `json:"date_updated,omitempty"`

	// A 34 character string that uniquely identifies this resource.
	Sid *string `json:"sid,omitempty"`

	// The URI for this resource, relative to https://api.twilio.com
	Uri *string `json:"uri,omitempty"`

	// The username for this credential.
	Username *string `json:"username,omitempty"`
}

// AssertApiV2010AccountSipSipCredentialListSipCredentialRequired checks if the required fields are not zero-ed
func AssertApiV2010AccountSipSipCredentialListSipCredentialRequired(obj ApiV2010AccountSipSipCredentialListSipCredential) error {
	return nil
}

// AssertRecurseApiV2010AccountSipSipCredentialListSipCredentialRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ApiV2010AccountSipSipCredentialListSipCredential (e.g. [][]ApiV2010AccountSipSipCredentialListSipCredential), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseApiV2010AccountSipSipCredentialListSipCredentialRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aApiV2010AccountSipSipCredentialListSipCredential, ok := obj.(ApiV2010AccountSipSipCredentialListSipCredential)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertApiV2010AccountSipSipCredentialListSipCredentialRequired(aApiV2010AccountSipSipCredentialListSipCredential)
	})
}
