/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ListRecordingResponse struct {

	End int32 `json:"end,omitempty"`

	FirstPageUri string `json:"first_page_uri,omitempty"`

	NextPageUri string `json:"next_page_uri,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	PreviousPageUri string `json:"previous_page_uri,omitempty"`

	Recordings []ApiV2010AccountRecording `json:"recordings,omitempty"`

	Start int32 `json:"start,omitempty"`

	Uri string `json:"uri,omitempty"`
}

// AssertListRecordingResponseRequired checks if the required fields are not zero-ed
func AssertListRecordingResponseRequired(obj ListRecordingResponse) error {
	for _, el := range obj.Recordings {
		if err := AssertApiV2010AccountRecordingRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListRecordingResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListRecordingResponse (e.g. [][]ListRecordingResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListRecordingResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListRecordingResponse, ok := obj.(ListRecordingResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListRecordingResponseRequired(aListRecordingResponse)
	})
}
