/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ListUsageRecordDailyResponse struct {

	End int32 `json:"end,omitempty"`

	FirstPageUri string `json:"first_page_uri,omitempty"`

	NextPageUri string `json:"next_page_uri,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	PreviousPageUri string `json:"previous_page_uri,omitempty"`

	Start int32 `json:"start,omitempty"`

	Uri string `json:"uri,omitempty"`

	UsageRecords []ApiV2010AccountUsageUsageRecordUsageRecordDaily `json:"usage_records,omitempty"`
}

// AssertListUsageRecordDailyResponseRequired checks if the required fields are not zero-ed
func AssertListUsageRecordDailyResponseRequired(obj ListUsageRecordDailyResponse) error {
	for _, el := range obj.UsageRecords {
		if err := AssertApiV2010AccountUsageUsageRecordUsageRecordDailyRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListUsageRecordDailyResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListUsageRecordDailyResponse (e.g. [][]ListUsageRecordDailyResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListUsageRecordDailyResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListUsageRecordDailyResponse, ok := obj.(ListUsageRecordDailyResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListUsageRecordDailyResponseRequired(aListUsageRecordDailyResponse)
	})
}
