/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ListAvailablePhoneNumberCountryResponse struct {

	Countries []ApiV2010AccountAvailablePhoneNumberCountry `json:"countries,omitempty"`

	End int32 `json:"end,omitempty"`

	FirstPageUri string `json:"first_page_uri,omitempty"`

	NextPageUri string `json:"next_page_uri,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	PreviousPageUri string `json:"previous_page_uri,omitempty"`

	Start int32 `json:"start,omitempty"`

	Uri string `json:"uri,omitempty"`
}

// AssertListAvailablePhoneNumberCountryResponseRequired checks if the required fields are not zero-ed
func AssertListAvailablePhoneNumberCountryResponseRequired(obj ListAvailablePhoneNumberCountryResponse) error {
	for _, el := range obj.Countries {
		if err := AssertApiV2010AccountAvailablePhoneNumberCountryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListAvailablePhoneNumberCountryResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListAvailablePhoneNumberCountryResponse (e.g. [][]ListAvailablePhoneNumberCountryResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListAvailablePhoneNumberCountryResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListAvailablePhoneNumberCountryResponse, ok := obj.(ListAvailablePhoneNumberCountryResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListAvailablePhoneNumberCountryResponseRequired(aListAvailablePhoneNumberCountryResponse)
	})
}
