/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ListNotificationResponse struct {

	End int32 `json:"end,omitempty"`

	FirstPageUri string `json:"first_page_uri,omitempty"`

	NextPageUri string `json:"next_page_uri,omitempty"`

	Notifications []ApiV2010AccountNotification `json:"notifications,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	PreviousPageUri string `json:"previous_page_uri,omitempty"`

	Start int32 `json:"start,omitempty"`

	Uri string `json:"uri,omitempty"`
}

// AssertListNotificationResponseRequired checks if the required fields are not zero-ed
func AssertListNotificationResponseRequired(obj ListNotificationResponse) error {
	for _, el := range obj.Notifications {
		if err := AssertApiV2010AccountNotificationRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListNotificationResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListNotificationResponse (e.g. [][]ListNotificationResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListNotificationResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListNotificationResponse, ok := obj.(ListNotificationResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListNotificationResponseRequired(aListNotificationResponse)
	})
}
