/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ApiV2010AccountAvailablePhoneNumberCountry struct {

	// Whether all phone numbers available in the country are new to the Twilio platform.
	Beta *bool `json:"beta,omitempty"`

	// The name of the country
	Country *string `json:"country,omitempty"`

	// The ISO-3166-1 country code of the country.
	CountryCode *string `json:"country_code,omitempty"`

	// A list of related resources identified by their relative URIs
	SubresourceUris *map[string]interface{} `json:"subresource_uris,omitempty"`

	// The URI of the Country resource, relative to `https://api.twilio.com`
	Uri *string `json:"uri,omitempty"`
}

// AssertApiV2010AccountAvailablePhoneNumberCountryRequired checks if the required fields are not zero-ed
func AssertApiV2010AccountAvailablePhoneNumberCountryRequired(obj ApiV2010AccountAvailablePhoneNumberCountry) error {
	return nil
}

// AssertRecurseApiV2010AccountAvailablePhoneNumberCountryRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ApiV2010AccountAvailablePhoneNumberCountry (e.g. [][]ApiV2010AccountAvailablePhoneNumberCountry), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseApiV2010AccountAvailablePhoneNumberCountryRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aApiV2010AccountAvailablePhoneNumberCountry, ok := obj.(ApiV2010AccountAvailablePhoneNumberCountry)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertApiV2010AccountAvailablePhoneNumberCountryRequired(aApiV2010AccountAvailablePhoneNumberCountry)
	})
}
