/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ListAuthorizedConnectAppResponse struct {

	AuthorizedConnectApps []ApiV2010AccountAuthorizedConnectApp `json:"authorized_connect_apps,omitempty"`

	End int32 `json:"end,omitempty"`

	FirstPageUri string `json:"first_page_uri,omitempty"`

	NextPageUri string `json:"next_page_uri,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	PreviousPageUri string `json:"previous_page_uri,omitempty"`

	Start int32 `json:"start,omitempty"`

	Uri string `json:"uri,omitempty"`
}

// AssertListAuthorizedConnectAppResponseRequired checks if the required fields are not zero-ed
func AssertListAuthorizedConnectAppResponseRequired(obj ListAuthorizedConnectAppResponse) error {
	for _, el := range obj.AuthorizedConnectApps {
		if err := AssertApiV2010AccountAuthorizedConnectAppRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListAuthorizedConnectAppResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListAuthorizedConnectAppResponse (e.g. [][]ListAuthorizedConnectAppResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListAuthorizedConnectAppResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListAuthorizedConnectAppResponse, ok := obj.(ListAuthorizedConnectAppResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListAuthorizedConnectAppResponseRequired(aListAuthorizedConnectAppResponse)
	})
}
