/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ListSipAuthCallsCredentialListMappingResponse struct {

	Contents []ApiV2010AccountSipSipDomainSipAuthSipAuthCallsSipAuthCallsCredentialListMapping `json:"contents,omitempty"`

	End int32 `json:"end,omitempty"`

	FirstPageUri string `json:"first_page_uri,omitempty"`

	NextPageUri string `json:"next_page_uri,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	PreviousPageUri string `json:"previous_page_uri,omitempty"`

	Start int32 `json:"start,omitempty"`

	Uri string `json:"uri,omitempty"`
}

// AssertListSipAuthCallsCredentialListMappingResponseRequired checks if the required fields are not zero-ed
func AssertListSipAuthCallsCredentialListMappingResponseRequired(obj ListSipAuthCallsCredentialListMappingResponse) error {
	for _, el := range obj.Contents {
		if err := AssertApiV2010AccountSipSipDomainSipAuthSipAuthCallsSipAuthCallsCredentialListMappingRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListSipAuthCallsCredentialListMappingResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListSipAuthCallsCredentialListMappingResponse (e.g. [][]ListSipAuthCallsCredentialListMappingResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListSipAuthCallsCredentialListMappingResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListSipAuthCallsCredentialListMappingResponse, ok := obj.(ListSipAuthCallsCredentialListMappingResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListSipAuthCallsCredentialListMappingResponseRequired(aListSipAuthCallsCredentialListMappingResponse)
	})
}
