/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * API version: 1.29.1
 * Contact: support@twilio.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ListRecordingTranscriptionResponse struct {

	End int32 `json:"end,omitempty"`

	FirstPageUri string `json:"first_page_uri,omitempty"`

	NextPageUri string `json:"next_page_uri,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"page_size,omitempty"`

	PreviousPageUri string `json:"previous_page_uri,omitempty"`

	Start int32 `json:"start,omitempty"`

	Transcriptions []ApiV2010AccountRecordingRecordingTranscription `json:"transcriptions,omitempty"`

	Uri string `json:"uri,omitempty"`
}

// AssertListRecordingTranscriptionResponseRequired checks if the required fields are not zero-ed
func AssertListRecordingTranscriptionResponseRequired(obj ListRecordingTranscriptionResponse) error {
	for _, el := range obj.Transcriptions {
		if err := AssertApiV2010AccountRecordingRecordingTranscriptionRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseListRecordingTranscriptionResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ListRecordingTranscriptionResponse (e.g. [][]ListRecordingTranscriptionResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseListRecordingTranscriptionResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aListRecordingTranscriptionResponse, ok := obj.(ListRecordingTranscriptionResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertListRecordingTranscriptionResponseRequired(aListRecordingTranscriptionResponse)
	})
}
